require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SignupEmailsController do

  # This should return the minimal set of attributes required to create a valid
  # SignupEmail. As you add validations to SignupEmail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SignupEmailsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all signup_emails as @signup_emails" do
      signup_email = SignupEmail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:signup_emails).should eq([signup_email])
    end
  end

  describe "GET show" do
    it "assigns the requested signup_email as @signup_email" do
      signup_email = SignupEmail.create! valid_attributes
      get :show, {:id => signup_email.to_param}, valid_session
      assigns(:signup_email).should eq(signup_email)
    end
  end

  describe "GET new" do
    it "assigns a new signup_email as @signup_email" do
      get :new, {}, valid_session
      assigns(:signup_email).should be_a_new(SignupEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested signup_email as @signup_email" do
      signup_email = SignupEmail.create! valid_attributes
      get :edit, {:id => signup_email.to_param}, valid_session
      assigns(:signup_email).should eq(signup_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SignupEmail" do
        expect {
          post :create, {:signup_email => valid_attributes}, valid_session
        }.to change(SignupEmail, :count).by(1)
      end

      it "assigns a newly created signup_email as @signup_email" do
        post :create, {:signup_email => valid_attributes}, valid_session
        assigns(:signup_email).should be_a(SignupEmail)
        assigns(:signup_email).should be_persisted
      end

      it "redirects to the created signup_email" do
        post :create, {:signup_email => valid_attributes}, valid_session
        response.should redirect_to(SignupEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved signup_email as @signup_email" do
        # Trigger the behavior that occurs when invalid params are submitted
        SignupEmail.any_instance.stub(:save).and_return(false)
        post :create, {:signup_email => {}}, valid_session
        assigns(:signup_email).should be_a_new(SignupEmail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SignupEmail.any_instance.stub(:save).and_return(false)
        post :create, {:signup_email => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested signup_email" do
        signup_email = SignupEmail.create! valid_attributes
        # Assuming there are no other signup_emails in the database, this
        # specifies that the SignupEmail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SignupEmail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => signup_email.to_param, :signup_email => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested signup_email as @signup_email" do
        signup_email = SignupEmail.create! valid_attributes
        put :update, {:id => signup_email.to_param, :signup_email => valid_attributes}, valid_session
        assigns(:signup_email).should eq(signup_email)
      end

      it "redirects to the signup_email" do
        signup_email = SignupEmail.create! valid_attributes
        put :update, {:id => signup_email.to_param, :signup_email => valid_attributes}, valid_session
        response.should redirect_to(signup_email)
      end
    end

    describe "with invalid params" do
      it "assigns the signup_email as @signup_email" do
        signup_email = SignupEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SignupEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => signup_email.to_param, :signup_email => {}}, valid_session
        assigns(:signup_email).should eq(signup_email)
      end

      it "re-renders the 'edit' template" do
        signup_email = SignupEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SignupEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => signup_email.to_param, :signup_email => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested signup_email" do
      signup_email = SignupEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => signup_email.to_param}, valid_session
      }.to change(SignupEmail, :count).by(-1)
    end

    it "redirects to the signup_emails list" do
      signup_email = SignupEmail.create! valid_attributes
      delete :destroy, {:id => signup_email.to_param}, valid_session
      response.should redirect_to(signup_emails_url)
    end
  end

end
